apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: greetings
spec:
  version: "v1.0.1"
  homepage: https://github.com/kgamanji/kubectl-greetings
  shortDescription: "Promt greetings message"
  description: |
     Promts greeting message
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    uri: https://github.com/kgamanji/kubectl-greetings/archive/v2.2.0.zip
    sha256: f6592862e6477faaf591f813c207e34339533503d98c4de82387ca4cd219ff7d 
    files:
    - from: "kubectl-greetings-*/*"
      to: "."
    bin: greetings.sh 
