apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: greetings
spec:
  version: "v1.0.0"
  homepage: https://github.com/kgamanji/kubectl-greetings
  shortDescription: "Promt greetings message"
  description: |
     Promts greeting message
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
    uri: https://github.com/kgamanji/kubectl-greetings/archive/v2.0.0.zip 
    sha256: 011e3ea52ed321527dde5a2201bbfe50452024ac3107972b9e15286899b5da3c 
    files:
    - from: "kubectl-greetings-*/*"
      to: "."
    bin: greetings.sh 
